apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
        - name: django
          image: cms/django:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5432