version: "3.3"

services:

  elasticsearch:
    image: bitnami/elasticsearch
    ports:
    - "9200:31000"

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/djangocms
    ports:
      - "5432:5432"
    depends_on:
      - db
      - elasticsearch
    links:
      - db:db
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.8.0
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/djangocms/logs:ro
    entrypoint: 'filebeat -e -strict.perms=false -d "*"'
    environment:
      ELASTICSEARCH_URL: https://172.26.113.205:31920 # Replace with IP and port for elasticsearch
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: password # Replace with elastic user password
    depends_on:
      - web