# Deprecated - for legacy version

version: "3.3"

services:

  swiftstack:
    image: swiftstack/picoswiftstack
    ports: 
      - "8080:8080"
  
  elasticsearch:
    image: bitnami/elasticsearch
    ports:
      - "9200:31000"

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  tika:
    image: apache/tika:1.25
    ports:
      - "9998:9998"
    command:
      - run
      - --cors
      - "*"

  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/djangocms
    ports:
      - "5432:5432"
    depends_on:
      - db
      - elasticsearch
      - swiftstack
      - tika
    links:
      - db:db