kind: Service
apiVersion: v1
metadata:
  name: django-service
  namespace: elastic
spec:
  type: NodePort
  selector:
    app: django-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432