apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster-cms
spec:
  version: 7.6.1
  nodeSets:
    - name: nodos-master
      count: 1
      config:
        node.master: true
        node.data: true
        node.ml: false
        node.store.allow_mmap: false
        node.attr.temp: hot
        node.max_local_storage_nodes: 2
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms500m -Xmx500m
              resources:
                requests:
                  cpu: 0.5
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: manual
    - name: nodos-datos
      count: 1
      config:
        node.master: false
        node.data: true
        node.ml: false
        node.store.allow_mmap: false
        node.attr.temp: warm
        node.max_local_storage_nodes: 2
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms500m -Xmx500m
              resources:
                requests:
                  cpu: 0.5
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: manual
  http:
    service:
      spec:
        type: NodePort
        ports:
          - port: 9200
            targetPort: 9200
            protocol: TCP
            nodePort: 31920