apiVersion: v1
kind: Namespace
metadata:
  name: testing-cms

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: testing-cms
  labels:
    app: elasticsearch
spec:
  type: NodePort
  ports:
    - port: 9200
      nodePort: 31000
      targetPort: 9200
  selector:
    app: elasticsearch

---
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: testing-cms
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels: 
        app: elasticsearch
    spec:
      containers:
       - name: elasticsearch
         image: bitnami/elasticsearch
         ports:
          - containerPort: 9200