apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika-deployment
  namespace: elastic
  labels:
    app: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
      - name: tika-container
        image: apache/tika:latest
        ports:
        - containerPort: 9998
