apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-cms
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: es-cluster-cms
  podTemplate:
    spec:
      containers:
        - name: kibana
  http:
    service:
      spec:
        type: NodePort
        ports:
          - port: 5601
            targetPort: 5601
            protocol: TCP
            nodePort: 31560