# Generated by Django 3.1.6 on 2021-04-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='indice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
