# Generated by Django 3.1.6 on 2021-04-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210422_1447'),
        ('search', '0006_auto_20210411_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='roles',
            field=models.ManyToManyField(to='users.Role'),
        ),
    ]
