# Generated by Django 3.1.6 on 2021-04-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_post_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='roles',
        ),
        migrations.AddField(
            model_name='post',
            name='roles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
