# Generated by Django 3.1.6 on 2021-05-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20210430_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
