# Generated by Django 3.1.6 on 2021-04-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('container', models.CharField(max_length=1024)),
                ('objectname', models.CharField(max_length=1024)),
            ],
            options={
                'unique_together': {('container', 'objectname')},
            },
        ),
    ]
