# Generated by Django 3.1.6 on 2021-04-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_storageobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorageObject',
        ),
    ]
