# Generated by Django 3.1.6 on 2021-03-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200501_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='challenger',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
    ]
