# Generated by Django 3.1.6 on 2021-04-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210308_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='arquitectura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='django',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='general',
            field=models.BooleanField(default=False),
        ),
    ]
