# Generated by Django 3.1.6 on 2021-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210411_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='arquitectura',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='django',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='general',
        ),
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='users.Role'),
        ),
    ]
