apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: cms
spec:
  type: NodePort
  selector:
    app: django-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
  namespace: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-container
  template:
    metadata:
      labels:
        app: django-container
    spec:
      containers:
        - name: django
          image: cms/django:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5432