apiVersion: v1
kind: Service
metadata:
  name: swift-service
  namespace: cms
spec:
  type: ClusterIP
  selector:
    app: swift-container
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift-deployment
  namespace: cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swift-container
  template:
    metadata:
      labels:
        app: swift-container
    spec:
      containers:
        - name: swift-container
          image: swiftstack/picoswiftstack
          ports:
            - port: 8080
              containerPort: 8080