apiVersion: v1
kind: Service
metadata:
  name: tika-service
  namespace: cms
spec:
  type: ClusterIP
  ports:
    - port: 9998
      targetPort: 9998
  selector:
    app: tika

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika-deployment
  namespace: cms
  labels:
    app: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
      - name: tika-container
        image: apache/tika:latest
        ports:
        - containerPort: 9998
