filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /djangocms/logs/*.log
output.elasticsearch: # Send logs to elasticsearch directly, will have to connect through logstash eventually
  hosts: ["${ELASTICSEARCH_URL}"]
  protocol: "https"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  ssl.verification_mode: none