apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deployment
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-container
  template:
    metadata:
      labels:
        app: elastic-container
    spec:
      containers:
        - name: elastic-container
          image: bitnami/elasticsearch
          ports:
              - containerPort: 9200